language: node_js
sudo: required
cache:
   directories:
     - node_modules
node_js:
  - 8
before_script:
  - npm install
script:
  - npm run gen
deploy:
  provider: pages
  local-dir: "public"
  repo: "skyFi/skyfi.github.io"
  target-branch: master
  project-name: "skyfi.github.io"
  email: "fyl_2525@163.com"
  name: "skylor"
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
